# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Europe/Berlin"
    labels:
      - "p:continuous-integration"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "Europe/Berlin"
    labels:
      - "p:dependencies"
    open-pull-requests-limit: 10
    reviewers:
      - "reactive-graph/code-contributors"
    groups:
      rust-dependencies:
        update-types:
          - "minor"
          - "patch"
