[package]
name = "reactive-graph-runtime-graphql-api"
description = "Reactive Graph - Runtime - GraphQL - API"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../../README.md"

[dependencies]
async-graphql = { workspace = true, features = ["uuid"] }
async-trait = { workspace = true }
serde_json = { workspace = true }
springtime-di = { workspace = true, features = ["threadsafe", "derive"] }

reactive-graph-lifecycle = { version = "0.10.0", path = "../../../lifecycle" }
reactive-graph-runtime-graphql-schema = { version = "0.10.0", path = "../schema" }

[lib]
crate-type = ["lib"]

[lints]
workspace = true
