[package]
name = "reactive-graph-dynamic-graph-impl"
description = "Reactive Graph - Dynamic Graph - Implementation"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../README.md"

[dependencies]
async-graphql = { workspace = true, features = ["uuid", "dynamic-schema"] }
async-trait = { workspace = true }
convert_case = { workspace = true }
log = { workspace = true, features = ["std", "serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
springtime-di = { workspace = true, features = ["threadsafe", "derive"] }
tokio = { workspace = true, features = ["macros", "time", "rt", "rt-multi-thread", "test-util"] }
uuid = { workspace = true, features = ["serde", "v4"] }

reactive-graph-graph = { version = "0.10.0", path = "../../graph" }
reactive-graph-lifecycle = { version = "0.10.0", path = "../../lifecycle" }
reactive-graph-type-system-api = { version = "0.10.0", path = "../../type-system/api" }
reactive-graph-runtime-model = { version = "0.10.0", path = "../../runtime/model" }
reactive-graph-dynamic-graph-model = { version = "0.10.0", path = "../model" }
reactive-graph-reactive-service-api = { version = "0.10.0", path = "../../reactive/service/api" }
reactive-graph-reactive-model-api = { version = "0.10.0", path = "../../reactive/model/api" }
reactive-graph-reactive-model-impl = { version = "0.10.0", path = "../../reactive/model/impl" }
reactive-graph-dynamic-graph-api = { version = "0.10.0", path = "../api" }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "time", "rt", "rt-multi-thread", "test-util"] }

reactive-graph-graph = { version = "0.10.0", path = "../../graph", features = ["test"] }

[lib]
crate-type = ["lib"]
