[package]
name = "reactive-graph-runtime-graphql-schema"
description = "Reactive Graph - Runtime - GraphQL - Schema"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../../README.md"

[dependencies]
async-graphql = { workspace = true, features = ["uuid"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

reactive-graph-graph = { version = "0.10.0", path = "../../../graph" }
reactive-graph-command-api = { version = "0.10.0", path = "../../../command/api" }
reactive-graph-command-model = { version = "0.10.0", path = "../../../command/model" }
reactive-graph-runtime-service-api = { version = "0.10.0", path = "../../service/api" }
reactive-graph-remotes-api = { version = "0.10.0", path = "../../../remotes/api" }
reactive-graph-remotes-model = { version = "0.10.0", path = "../../../remotes/model" }

[dev-dependencies]
reactive-graph-graph = { version = "0.10.0", path = "../../../graph", features = ["test"] }

[lib]
crate-type = ["lib"]

[lints]
workspace = true
