[package]
name = "reactive-graph-runtime-types"
description = "Reactive Graph - Runtime - Types"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../README.md"

[dependencies]
json5 = { workspace = true, optional = true }
log = { workspace = true, features = ["std", "serde"] }
rust-embed = { workspace = true, features = ["debug-embed", "compression"] }
springtime-di = { workspace = true, features = ["threadsafe", "derive"] }
toml = { workspace = true, optional = true }

reactive-graph-graph = { version = "0.10.0", path = "../../graph" }
reactive-graph-type-system-api = { version = "0.10.0", path = "../../type-system/api" }

[features]
default = ["json5", "toml"]
json5 = ["dep:json5", "reactive-graph-type-system-api/json5"]
toml = ["dep:toml", "reactive-graph-type-system-api/toml"]

[lib]
crate-type = ["lib"]

[lints]
workspace = true
