[package]
name = "reactive-graph-dynamic-graph-json-schema"
description = "Reactive Graph - Dynamic Graph - JSON Schema"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../README.md"

[dependencies]
default-test = { workspace = true, optional = true }
schemars = { workspace = true, features = ["uuid1"] }
serde_json = { workspace = true }

reactive-graph-graph = { version = "0.10.0", path = "../../graph" }
reactive-graph-utils-test = { version = "0.10.0", path = "../../utils/test", optional = true }

[dev-dependencies]
default-test = { workspace = true }

reactive-graph-graph = { version = "0.10.0", path = "../../graph", features = ["test"] }
reactive-graph-utils-test = { version = "0.10.0", path = "../../utils/test" }

[features]
test = ["default-test", "reactive-graph-utils-test"]

[lib]
crate-type = ["lib"]

[lints]
workspace = true
