.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH reactive-graph-tooling 1  "reactive-graph-tooling 0.10.0" 
.SH NAME
reactive\-graph\-tooling \- Reactive Graph is a reactive runtime based on a graph database, empowering everyone to build reliable and efficient software.
.SH SYNOPSIS
\fBreactive\-graph\-tooling\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Reactive Graph is a reactive runtime based on a graph database, empowering everyone to build reliable and efficient software.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
reactive\-graph\-tooling\-shell\-completions(1)
Prints or installs Shell completions
.TP
reactive\-graph\-tooling\-man\-pages(1)
Prints or installs man pages
.TP
reactive\-graph\-tooling\-print\-markdown\-help(1)
Prints the markdown help to stdout
.TP
reactive\-graph\-tooling\-info(1)
Prints info about this binary
.TP
reactive\-graph\-tooling\-instances(1)
Manage instances
.TP
reactive\-graph\-tooling\-update(1)
Update the Reactive Graph binary
.TP
reactive\-graph\-tooling\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.10.0
.SH AUTHORS
Andreas Schaeffer <hanack@nooblounge.net>

