.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH reactive-graph-client 1  "reactive-graph-client 0.10.0" 
.SH NAME
reactive\-graph\-client \- Reactive Graph is a reactive runtime based on a graph database, empowering everyone to build reliable and efficient software.
.SH SYNOPSIS
\fBreactive\-graph\-client\fR [\fB\-\-client\-hostname\fR] [\fB\-\-client\-port\fR] [\fB\-\-client\-secure\fR] [\fB\-\-endpoint\-graphql\fR] [\fB\-\-endpoint\-dynamic\-graph\fR] [\fB\-\-endpoint\-runtime\fR] [\fB\-\-endpoint\-plugins\fR] [\fB\-\-bearer\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Reactive Graph is a reactive runtime based on a graph database, empowering everyone to build reliable and efficient software.
.SH OPTIONS
.TP
\fB\-\-client\-hostname\fR=\fICLIENT_HOSTNAME\fR
The hostname to connect to
.TP
\fB\-\-client\-port\fR=\fICLIENT_PORT\fR
The port to connect to
.TP
\fB\-\-client\-secure\fR=\fICLIENT_SECURE\fR
If true, connects via HTTPS
.br

.br
[\fIpossible values: \fRtrue, false]
.TP
\fB\-\-endpoint\-graphql\fR=\fIENDPOINT_GRAPHQL\fR
The endpoint to use
.TP
\fB\-\-endpoint\-dynamic\-graph\fR=\fIENDPOINT_DYNAMIC_GRAPH\fR
The endpoint to use
.TP
\fB\-\-endpoint\-runtime\fR=\fIENDPOINT_RUNTIME\fR
The endpoint to use
.TP
\fB\-\-endpoint\-plugins\fR=\fIENDPOINT_PLUGINS\fR
The endpoint to use
.TP
\fB\-\-bearer\fR=\fIBEARER\fR
The authentication token
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
reactive\-graph\-client\-shell\-completions(1)
Prints or installs Shell completions
.TP
reactive\-graph\-client\-man\-pages(1)
Prints or installs man pages
.TP
reactive\-graph\-client\-print\-markdown\-help(1)
Prints the markdown help to stdout
.TP
reactive\-graph\-client\-info(1)
Prints info about this binary
.TP
reactive\-graph\-client\-execute\-command(1)
Executes a command on the client
.TP
reactive\-graph\-client\-instance\-info(1)
Prints information about the instance
.TP
reactive\-graph\-client\-plugins(1)
Manage plugins
.TP
reactive\-graph\-client\-remotes(1)
Manage remotes
.TP
reactive\-graph\-client\-shutdown(1)
Shutdown the runtime
.TP
reactive\-graph\-client\-components(1)
Manage components
.TP
reactive\-graph\-client\-entity\-types(1)
Manage entity types
.TP
reactive\-graph\-client\-relation\-types(1)
Manage entity types
.TP
reactive\-graph\-client\-flow\-types(1)
Manage entity types
.TP
reactive\-graph\-client\-entity\-instances(1)
Manage entity instances
.TP
reactive\-graph\-client\-relation\-instances(1)
Manage relation instances
.TP
reactive\-graph\-client\-flow\-instances(1)
Manage flow instances
.TP
reactive\-graph\-client\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.10.0
.SH AUTHORS
Andreas Schaeffer <hanack@nooblounge.net>

