[package]
name = "reactive-graph-behaviour-service-impl"
description = "Reactive Graph - Behaviour - Service - Implementation"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../../README.md"

[dependencies]
async-trait = { workspace = true }
dashmap = { workspace = true }
log = { workspace = true, features = ["std", "serde"] }
springtime-di = { workspace = true, features = ["threadsafe", "derive"] }
uuid = { workspace = true, features = ["serde", "v4"] }

reactive-graph-behaviour-model-api = { version = "0.10.0", path = "../../model/api" }
reactive-graph-behaviour-model-impl = { version = "0.10.0", path = "../../model/impl" }
reactive-graph-behaviour-service-api = { version = "0.10.0", path = "../api" }
reactive-graph-graph = { version = "0.10.0", path = "../../../graph" }
reactive-graph-lifecycle = { version = "0.10.0", path = "../../../lifecycle" }
reactive-graph-reactive-model-api = { version = "0.10.0", path = "../../../reactive/model/api" }
reactive-graph-reactive-model-impl = { version = "0.10.0", path = "../../../reactive/model/impl" }
reactive-graph-type-system-api = { version = "0.10.0", path = "../../../type-system/api" }

[lib]
crate-type = ["lib"]

[lints]
workspace = true
