[package]
name = "reactive-graph-generator-documentation"
description = "Reactive Graph - Generator - Documentation"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../README.md"

[dependencies]
#anyhow = { workspace = true }
documented = { workspace = true }
markdown-builder = "1.0.0"
serde_json = { workspace = true }
tabled = { workspace = true }
thiserror = { workspace = true }
workspace_root = { workspace = true }

#reactive-graph-instance-system-json-schema = { version = "0.10.0", path = "../../instance-system/json-schema" }
reactive-graph-graph = { version = "0.10.0", path = "../../graph", features = ["docs"] }
#reactive-graph-table-model = { version = "0.10.0", path = "../../table-model" }
#reactive-graph-runtime-impl = { version = "0.10.0", path = "../../runtime/impl" }
#reactive-graph-type-system-json-schema = { version = "0.10.0", path = "../../type-system/json-schema" }

[dev-dependencies]
default-test = { workspace = true }

reactive-graph-graph = { version = "0.10.0", path = "../../graph", features = ["test", "docs"] }

[lib]
crate-type = ["lib"]

[lints]
workspace = true
