[package]
name = "reactive-graph-instance-system-rest"
description = "Reactive Graph - Instance System - REST API"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../README.md"

[dependencies]
actix-web = { workspace = true, features = ["rustls-0_23"] }
mime = { workspace = true }
schemars = { workspace = true, features = ["uuid1"] }

reactive-graph-graph = { version = "0.10.0", path = "../../graph" }
reactive-graph-instance-system-api = { version = "0.10.0", path = "../api" }
reactive-graph-instance-system-json-schema = { version = "0.10.0", path = "../json-schema" }

[lib]
crate-type = ["lib"]

[lints]
workspace = true
