[package]
name = "reactive-graph-remotes-impl"
description = "Reactive Graph - Remotes - Implementation"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../README.md"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }
gql_client = { workspace = true, features = ["rustls-tls"], default-features = false }
log = { workspace = true, features = ["std", "serde"] }
serde = { workspace = true }
springtime-di = { workspace = true, features = ["threadsafe", "derive"] }

reactive-graph-remotes-api = { version = "0.10.0", path = "../api" }
reactive-graph-remotes-model = { version = "0.10.0", path = "../model" }
reactive-graph-config-api = { version = "0.10.0", path = "../../config/api" }
reactive-graph-config-model = { version = "0.10.0", path = "../../config/model" }
reactive-graph-plugin-api = { version = "0.10.0", path = "../../plugin/api" }
reactive-graph-lifecycle = { version = "0.10.0", path = "../../lifecycle" }

[dev-dependencies]
reactive-graph-di = { version = "0.10.0", path = "../../di" }

[build-dependencies]
anyhow = { workspace = true }
vergen-gix = { workspace = true, features = ["build", "cargo", "rustc", "si"] }

[lib]
crate-type = ["lib"]

[lints]
workspace = true
