hostname = "localhost"
port = 31415

# Enable HTTPS and WSS
secure = false

# Certificate path
ssl_certificate_path = "./keys/cert.pem"
# Private key path
ssl_private_key_path = "./keys/cert.key.pem"

# Timeout for graceful workers shutdown in seconds.
# After receiving a stop signal, workers have this much time to finish serving requests. Workers still alive after the
# timeout are force dropped.
# By default, shutdown timeout sets to 30 seconds.
shutdown_timeout = 3

# Set number of workers to start.
# The default worker count is the number of physical CPU cores available.
workers = 16

# Web resource provider which is the base
# default_context_path = "graphql-client"
# default_context_path = "graphql-schema-visualization"
# default_context_path = "playground"

[logging]

enabled = true

# Log format https://docs.rs/actix-web/0.6.0/actix_web/middleware/struct.Logger.html#format
#format = "%a \"%r\" %s %b \"%{Referer}i\" \"%{User-Agent}i\" %T"
