[package]
name = "reactive-graph-instance-system-json-schema"
description = "Reactive Graph - Instance System - JSON Schema"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../README.md"

[dependencies]
schemars = { workspace = true, features = ["uuid1"] }

reactive-graph-graph = { version = "0.10.0", path = "../../graph" }

[lib]
crate-type = ["lib"]

[lints]
workspace = true
