[package]
name = "reactive-graph-remotes-api"
description = "Reactive Graph - Remotes - API"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../README.md"

[dependencies]
async-trait = { workspace = true }
gql_client = { workspace = true, features = ["rustls-tls"], default-features = false }
springtime-di = { workspace = true, features = ["threadsafe", "derive"] }
thiserror = { workspace = true }

reactive-graph-lifecycle = { version = "0.10.0", path = "../../lifecycle" }
reactive-graph-remotes-model = { version = "0.10.0", path = "../model" }
reactive-graph-config-api = { version = "0.10.0", path = "../../config/api" }

[lib]
crate-type = ["lib"]

[lints]
workspace = true
