[package]
name = "reactive-graph-graphql-impl"
description = "Reactive Graph - GraphQL - Service - Implementation"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../README.md"

[dependencies]
async-graphql = { workspace = true, features = ["uuid"] }
async-trait = { workspace = true }
log = { workspace = true, features = ["std", "serde"] }
serde_json = { workspace = true }
springtime-di = { workspace = true, features = ["threadsafe", "derive"] }

reactive-graph-di = { version = "0.10.0", path = "../../di" }
reactive-graph-graphql-schema = { version = "0.10.0", path = "../schema" }
reactive-graph-graphql-api = { version = "0.10.0", path = "../api" }
reactive-graph-lifecycle = { version = "0.10.0", path = "../../lifecycle" }
reactive-graph-type-system-api = { version = "0.10.0", path = "../../type-system/api" }
reactive-graph-behaviour-service-api = { version = "0.10.0", path = "../../behaviour/service/api" }
reactive-graph-reactive-service-api = { version = "0.10.0", path = "../../reactive/service/api" }

[dev-dependencies]

[lib]
crate-type = ["lib"]
