[package]
name = "reactive-graph-model-flow"
description = "Reactive Graph - Model - Flow"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../README.md"

[dependencies]
reactive-graph-graph = { version = "0.10.0", path = "../../graph" }

[lib]
crate-type = ["lib"]

[lints]
workspace = true
