[package]
name = "reactive-graph-runtime-api"
description = "Reactive Graph - Runtime - API"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../README.md"
keywords = [
    "reactive",
    "graph",
    "flow",
    "entity-system",
    "ecs"
]

[dependencies]
async-trait = { workspace = true }
springtime-di = { workspace = true, features = ["threadsafe", "derive"] }
tokio = { workspace = true, features = ["macros", "time", "rt", "rt-multi-thread", "test-util"] }

reactive-graph-lifecycle = { version = "0.10.0", path = "../../lifecycle" }
reactive-graph-config-api = { version = "0.10.0", path = "../../config/api" }
reactive-graph-type-system-api = { version = "0.10.0", path = "../../type-system/api" }
reactive-graph-instance-system-api = { version = "0.10.0", path = "../../instance-system/api" }
reactive-graph-reactive-service-api = { version = "0.10.0", path = "../../reactive/service/api" }
reactive-graph-behaviour-service-api = { version = "0.10.0", path = "../../behaviour/service/api" }
reactive-graph-runtime-service-api = { version = "0.10.0", path = "../service/api" }
reactive-graph-runtime-graphql-api = { version = "0.10.0", path = "../graphql/api" }
reactive-graph-runtime-web-api = { version = "0.10.0", path = "../web/api" }
reactive-graph-graphql-api = { version = "0.10.0", path = "../../graphql/api" }
reactive-graph-dynamic-graph-api = { version = "0.10.0", path = "../../dynamic-graph/api" }
reactive-graph-plugin-service-api = { version = "0.10.0", path = "../../plugin/service/api" }
reactive-graph-plugin-graphql-api = { version = "0.10.0", path = "../../plugin/graphql/api" }
reactive-graph-command-api = { version = "0.10.0", path = "../../command/api" }
reactive-graph-remotes-api = { version = "0.10.0", path = "../../remotes/api" }
reactive-graph-remotes-model = { version = "0.10.0", path = "../../remotes/model" }

[dev-dependencies]

[features]
test = []

[lib]
crate-type = ["lib"]

[lints]
workspace = true
