[package]
name = "reactive-graph-reactive-model-impl"
description = "Reactive Graph - Reactive Model - Implementation"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../../README.md"

[dependencies]
dashmap = { workspace = true, features = ["rayon"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
typed-builder = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

reactive-graph-graph = { version = "0.10.0", path = "../../../graph" }
reactive-graph-behaviour-model-api = { version = "0.10.0", path = "../../../behaviour/model/api" }
reactive-graph-reactive-model-api = { version = "0.10.0", path = "../api" }
reactive-graph-utils-test = { version = "0.10.0", path = "../../../utils/test", optional = true }

[dev-dependencies]
criterion = { workspace = true, features = ["html_reports"] }
rand = { workspace = true }
stopwatch2 = { workspace = true }

reactive-graph-utils-test = { version = "0.10.0", path = "../../../utils/test" }

[lib]
crate-type = ["lib"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

[[bench]]
name = "reactive_property_instance_stream"
harness = false
