name: Add Labels

on:
  issues:
    types: [ opened ]

jobs:
  add_labels:
    runs-on: ubuntu-22.04
    steps:
      - name: Add labels
        uses: andymckay/labeler@master
        with:
          add-labels: "o:triage"
          ignore-if-labeled: true
