name: Security audit
on:
  push:
    branches: [ main ]
    paths:
      - "crates/**/Cargo.toml"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/audit.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "crates/**/Cargo.toml"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/audit.yml"
  schedule:
    - cron: "0 12 * * 0"
  # Run manually
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-22.04
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v5
      - name: Audit Rust Dependencies
        uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
