name: Label Sync

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  label_sync:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/labels.yml
      - uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
