name: Mark stale pull requests

on:
  schedule:
    - cron: '35 19 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-pr-stale: 28
          days-before-issue-stale: -1   # don't mark issues as stale
          exempt-draft-pr: true         # don't mark draft PRs as stale
          days-before-close: -1         # don't close stale PRs/issues
          stale-pr-label: o:stale
          stale-pr-message: >
            This PR has not had activity in the past 4 weeks, labeling it as stale.
            If the PR is waiting for review, notify the dev@lucene.apache.org list.
            Thank you for your contribution!
          debug-only: false             # turn on to run the action without applying changes
          operations-per-run: 500       # operations budget
