name: Schema

on:
  push:
    branches: [ main ]
    paths:
      - "schema/**/*.graphql"
      - "schema/**/*.schema.json"
      - ".github/workflows/schema.yml"

jobs:
  docs:
    name: Publish Schema
    runs-on: ubuntu-22.04
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v5
      - name: Deploy schemas to docs.reactive-graph.io
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./schema
          destination_dir: schema
          # keep_files: true
      - name: Deploy schemas to schema.reactive-graph.io
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          deploy_key: ${{ secrets.DEPLOY_SCHEMA_KEY }}
          external_repository: reactive-graph/schema
          publish_dir: ./schema
          destination_dir: schema
          # keep_files: true
